### ISSUE TITLE
Issue: Giacomo spams useless iOS config files :(

### ISSUE THREAD

**Issue by PlasmaStark** [giacomoborin/Beamer-Theme#14]
Ho creato il file `.gitignore`, github lo usa per ignorare dei files irrilevanti quando fai upload; consiglio di farlo appena crei il progetto la prossima volta.
Esempio:

> `# Files di log di Giacomo, che si ostina ad usare prodotti Apple e mi spamma`
> `# i log delle configurazioni cartelle iOS:`
> `.DS_Store`

[file .gitignore](https://github.com/giacomoborin/Beamer-Theme/blob/main/.gitignore)

**Comment by giacomoborin** [comment]
ops 🍎
Devo aggiungerci qualcosa?

**Comment by PlasmaStark** [comment]
No, ho fatto io, era giusto per fartelo sapere in vista delle cose future 
Il gitignore serve!
