### ISSUE TITLE
Issue: style

### ISSUE THREAD

**Issue by PlasmaStark** [giacomoborin/Beamer-Theme#6]
Sarebbe interessante sistemare lo stile del documento, ad esempio:

- [x] Cursori e frecce in basso (per ogni slide?)
- [x] Non avere il frame con il titolo delle sezioni così vuoto
- [x] Sistemare alcuni oggetti per renderli più "interessanti", ad esempio i box troppo standard

**Comment by giacomoborin** [comment]
Ho fatto la footline, molto standard ma penso vada bene. Ci sono solo le pagine che mi sembrano 1 pt più in basso rispetto ai bottoni

- [ ] allineare le pagine

**Comment by giacomoborin** [comment]
Ho aggiunto un color theme che li rende più carini, però ci sarebbero tre cose da vedere
- [x] Controllare che non abbia fatto danni
- [x] Vedere se sono meglio rotondi o quadrati 
- [x] Ombra o non ombra, questo è il dilemma

**Comment by PlasmaStark** [comment]
Ho caricato il theme, non ha fatto danni, anzi è molto carino... direi che rotondo si confà allo stile generale del theme e l'ombra crea una buona profondità, la terrei. 
Unica cosa: non so quanto mi convincano i colori delle alertboxes, un po' troppo rosato

**Comment by PlasmaStark** [comment]
Per me possiamo anche chiudere questo issue, se concordi spunta tutto e chiudi

**Comment by giacomoborin** [comment]
Mancherebbe allineare le pagine nella foot line

**Comment by PlasmaStark** [comment]
Hai ragione, non lo avevo visto... 😬 
Cosa intendi con foot line? Non ho inteso bene @giacomoborin

**Comment by PlasmaStark** [comment]
![immagine](https://user-images.githubusercontent.com/64229723/115884662-71969e00-a44f-11eb-828d-d36f6e2d0299.png)
Titolo in grassetto? Com'è?

- [x] valutare se fare il titolo in grassetto automatico (o lasciare decidere all'utente)

**Comment by giacomoborin** [comment]
Meglio in grassetto automatico secondo me

**Comment by PlasmaStark** [comment]
Concordo, già che ci sono modifico l'impostazione nello _Stark style update_

**Comment by PlasmaStark** [comment]
Chiudo l'issue dato che abbiamo visto tutto, al massimo ne apriamo un altro.
