### ISSUE TITLE
Bibliography overfull on the footline

### ISSUE THREAD

**Issue by giacomoborin** [giacomoborin/Beamer-Theme#8]
As you can see if the bibliography is too long it goes over the footline
<img width="767" alt="image" src="https://user-images.githubusercontent.com/64214430/115368400-54e83500-a1c7-11eb-8266-db2044988a4f.png">

**Comment by giacomoborin** [comment]
Si risolve dando la possibilità per quel frame di dividersi con 
`[allowframebreaks]`
Inoltre è necessario specificare
`\printbibliography[heading=none]`

**Comment by giacomoborin** [comment]
Forse si può trovare il modo di impostarli in automatico, ma non so se avrebbe senso

**Comment by PlasmaStark** [comment]
In realtà direi di no, sembra sia un problema comune 
A questo punto direi di lasciarlo così

**Comment by giacomoborin** [comment]
ok aggiungiamo una nota da qualche parte magari

**Comment by PlasmaStark** [comment]
Provvedo a creare un readme per il template (non per il progetto, proprio per chi usa il template; lo mettiamo nella release)
