### ISSUE TITLE
Block can go over the bar

### ISSUE THREAD

**Issue by giacomoborin** [giacomoborin/Beamer-Theme#9]
The image show clearly the bug, but I don't think is so severe
<img width="264" alt="image" src="https://user-images.githubusercontent.com/64214430/115368997-ef487880-a1c7-11eb-9888-809ed43c21fe.png">

**Comment by PlasmaStark** [comment]
Issue o caso patologico? Non so se a quel punto sia colpa dell'utente o meno

**Comment by giacomoborin** [comment]
Il problema è più l'ombra secondo me,
Comunque è una cosa piccola quindi non così importante

**Comment by PlasmaStark** [comment]
> Il problema è più l'ombra secondo me,

Ti dirò, non mi dispiace più di tanto, ma sicuramente prima o poi servirà sentire altri pareri... ad esempio il professore

> Comunque è una cosa piccola quindi non così importante

Se fosse un problema proveremo a risolvere, ma non so quanto sia semplice, [apparentemente non troppo](https://tex.stackexchange.com/questions/3139/beamer-how-to-remove-shadow-under-the-title-on-a-given-frame)
